SOLVER:
  BASE_LR: 0.01
  WEIGHT_DECAY: 0.0001
  IMS_PER_BATCH: 64
  MAX_EPOCHS: 2

TEST:
  IMS_PER_BATCH: 64

DATASETS:
  TRAIN_ROOT: '/home/ahab/datasets/MNIST_ImageFolder/train'

OUTPUT_ROOT: '/home/ahab/results/'
EXPERIMENT_NAME: 'MNIST-baseline'